/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Usado pelo healthcheck do Docker e por monitores externos.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/contratacoes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar Contratacoes
     * @description Lista contratações com filtros combináveis, paginação e ordenação.
     */
    get: operations["listar_contratacoes_contratacoes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/contratacoes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detalhar Contratacao
     * @description Detalhe de uma contratação, com o órgão e todos os itens (e o vencedor de cada um).
     */
    get: operations["detalhar_contratacao_contratacoes__id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/orgaos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar Orgaos
     * @description Órgãos em ordem alfabética. Com `uf`, só os que publicaram contratações na UF.
     */
    get: operations["listar_orgaos_orgaos_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/categorias": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar Categorias
     * @description Categorias (tipo + capítulo NCM/NBS). Use `ncm_capitulo` no filtro `categoria`.
     */
    get: operations["listar_categorias_categorias_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metricas/valor-mensal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Valor Mensal
     * @description Valor estimado contratado por mês, com média móvel de 3 meses (sem buracos).
     */
    get: operations["valor_mensal_metricas_valor_mensal_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metricas/preco-categoria": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Preco Categoria
     * @description Preço mediano por categoria, unidade e mês, com a variação sobre o mês anterior.
     */
    get: operations["preco_categoria_metricas_preco_categoria_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metricas/ranking-fornecedores": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ranking Fornecedores
     * @description Ranking dos fornecedores de cada órgão pelo valor homologado.
     */
    get: operations["ranking_fornecedores_metricas_ranking_fornecedores_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metricas/precos-acima-p90": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Precos Acima P90
     * @description Itens com preço no percentil 90 ou acima entre os comparáveis (base do sobrepreço).
     *
     *     Só entram itens de categoria classificada (com NCM) e grupos com amostra mínima.
     */
    get: operations["precos_acima_p90_metricas_precos_acima_p90_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CategoriaResponse */
    CategoriaResponse: {
      material_ou_servico: components["schemas"]["MaterialOuServico"];
      /**
       * Ncm Capitulo
       * @description Valor para o filtro `categoria`; null = sem classificação (não filtrável)
       */
      ncm_capitulo: string | null;
      /** Nome */
      nome: string;
    };
    /** ContratacaoDetalheResponse */
    ContratacaoDetalheResponse: {
      /**
       * Id
       * @description Id público: número de controle PNCP com '-' no lugar de '/'
       */
      id: string;
      /** Numero Controle Pncp */
      numero_controle_pncp: string;
      orgao: components["schemas"]["OrgaoRefResponse"];
      /** Modalidade */
      modalidade: number;
      /** Modalidade Nome */
      modalidade_nome: string;
      /** Situacao */
      situacao: number;
      /** Situacao Nome */
      situacao_nome: string;
      /** Objeto */
      objeto: string;
      /**
       * Valor Total Estimado
       * @description null = orçamento sigiloso
       */
      valor_total_estimado: string | null;
      /**
       * Data Publicacao
       * Format: date-time
       */
      data_publicacao: string;
      /** Uf */
      uf: string;
      /** Municipio */
      municipio: string;
      /** Total Itens */
      total_itens: number;
      /** Itens */
      itens: components["schemas"]["ItemResponse"][];
    };
    /** ContratacaoResponse */
    ContratacaoResponse: {
      /**
       * Id
       * @description Id público: número de controle PNCP com '-' no lugar de '/'
       */
      id: string;
      /** Numero Controle Pncp */
      numero_controle_pncp: string;
      orgao: components["schemas"]["OrgaoRefResponse"];
      /** Modalidade */
      modalidade: number;
      /** Modalidade Nome */
      modalidade_nome: string;
      /** Situacao */
      situacao: number;
      /** Situacao Nome */
      situacao_nome: string;
      /** Objeto */
      objeto: string;
      /**
       * Valor Total Estimado
       * @description null = orçamento sigiloso
       */
      valor_total_estimado: string | null;
      /**
       * Data Publicacao
       * Format: date-time
       */
      data_publicacao: string;
      /** Uf */
      uf: string;
      /** Municipio */
      municipio: string;
      /** Total Itens */
      total_itens: number;
    };
    /**
     * Esfera
     * @enum {string}
     */
    Esfera: "F" | "E" | "M" | "D" | "N";
    /** FornecedorResponse */
    FornecedorResponse: {
      /** Documento */
      documento: string;
      /** Nome */
      nome: string;
      tipo_pessoa: components["schemas"]["TipoPessoa"];
      /** Tipo Pessoa Nome */
      tipo_pessoa_nome: string;
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** ItemResponse */
    ItemResponse: {
      /** Numero Item */
      numero_item: number;
      /** Descricao */
      descricao: string;
      material_ou_servico: components["schemas"]["MaterialOuServico"];
      /** Material Ou Servico Nome */
      material_ou_servico_nome: string;
      /** Ncm Nbs */
      ncm_nbs: string | null;
      /** Quantidade */
      quantidade: string;
      /** Unidade Medida */
      unidade_medida: string;
      /**
       * Valor Unitario Estimado
       * @description null = orçamento sigiloso
       */
      valor_unitario_estimado: string | null;
      /** Valor Total Estimado */
      valor_total_estimado: string | null;
      /** @description null = ainda sem resultado */
      vencedor: components["schemas"]["FornecedorResponse"] | null;
      /** Valor Unitario Homologado */
      valor_unitario_homologado: string | null;
    };
    /**
     * MaterialOuServico
     * @enum {string}
     */
    MaterialOuServico: "M" | "S";
    /**
     * Ordenacao
     * @description Ordenações aceitas. O `-` na frente é decrescente (convenção comum em APIs).
     * @enum {string}
     */
    Ordenacao:
      "-data_publicacao" | "data_publicacao" | "-valor_total_estimado" | "valor_total_estimado";
    /** OrgaoRefResponse */
    OrgaoRefResponse: {
      /** Cnpj */
      cnpj: string;
      /** Razao Social */
      razao_social: string;
    };
    /** OrgaoResponse */
    OrgaoResponse: {
      /** Cnpj */
      cnpj: string;
      /** Razao Social */
      razao_social: string;
      esfera: components["schemas"]["Esfera"];
      /** Esfera Nome */
      esfera_nome: string;
      poder: components["schemas"]["Poder"];
      /** Poder Nome */
      poder_nome: string;
      /** Total Contratacoes */
      total_contratacoes: number;
    };
    /** PaginaResponse[ContratacaoResponse] */
    PaginaResponse_ContratacaoResponse_: {
      /** Itens */
      itens: components["schemas"]["ContratacaoResponse"][];
      /**
       * Total
       * @description Registros que atendem ao filtro, em todas as páginas
       */
      total: number;
      /** Pagina */
      pagina: number;
      /** Tamanho Pagina */
      tamanho_pagina: number;
      /** Total Paginas */
      total_paginas: number;
    };
    /** PaginaResponse[OrgaoResponse] */
    PaginaResponse_OrgaoResponse_: {
      /** Itens */
      itens: components["schemas"]["OrgaoResponse"][];
      /**
       * Total
       * @description Registros que atendem ao filtro, em todas as páginas
       */
      total: number;
      /** Pagina */
      pagina: number;
      /** Tamanho Pagina */
      tamanho_pagina: number;
      /** Total Paginas */
      total_paginas: number;
    };
    /** PaginaResponse[PrecoAcimaP90Response] */
    PaginaResponse_PrecoAcimaP90Response_: {
      /** Itens */
      itens: components["schemas"]["PrecoAcimaP90Response"][];
      /**
       * Total
       * @description Registros que atendem ao filtro, em todas as páginas
       */
      total: number;
      /** Pagina */
      pagina: number;
      /** Tamanho Pagina */
      tamanho_pagina: number;
      /** Total Paginas */
      total_paginas: number;
    };
    /**
     * Poder
     * @enum {string}
     */
    Poder: "E" | "L" | "J" | "N";
    /** PrecoAcimaP90Response */
    PrecoAcimaP90Response: {
      /**
       * Contratacao Id
       * @description Id público, para GET /contratacoes/{id}
       */
      contratacao_id: string;
      /** Numero Controle Pncp */
      numero_controle_pncp: string;
      /** Numero Item */
      numero_item: number;
      /** Orgao Razao Social */
      orgao_razao_social: string;
      /** Categoria Nome */
      categoria_nome: string;
      /** Unidade */
      unidade: string;
      /**
       * Data Publicacao
       * Format: date
       */
      data_publicacao: string;
      /** Valor Unitario Estimado */
      valor_unitario_estimado: string;
      /**
       * Percentil Preco
       * @description 0 = mais barato, 1 = mais caro do grupo
       */
      percentil_preco: string;
      /** Itens Comparaveis */
      itens_comparaveis: number;
    };
    /** PrecoCategoriaResponse */
    PrecoCategoriaResponse: {
      categoria: components["schemas"]["CategoriaResponse"];
      /** Unidade */
      unidade: string;
      /**
       * Mes
       * Format: date
       */
      mes: string;
      /** Itens */
      itens: number;
      /** Preco Medio */
      preco_medio: string;
      /** Preco Mediano */
      preco_mediano: string;
      /**
       * Preco Mediano Mes Anterior
       * @description null quando o mês imediatamente anterior não teve itens
       */
      preco_mediano_mes_anterior: string | null;
      /** Variacao Percentual */
      variacao_percentual: string | null;
    };
    /** RankingFornecedorResponse */
    RankingFornecedorResponse: {
      /** Orgao Cnpj */
      orgao_cnpj: string;
      /** Orgao Razao Social */
      orgao_razao_social: string;
      /** Fornecedor Documento */
      fornecedor_documento: string;
      /** Fornecedor Nome */
      fornecedor_nome: string;
      /** Itens Vencidos */
      itens_vencidos: number;
      /** Valor Total Homologado */
      valor_total_homologado: string;
      /**
       * Ranking
       * @description RANK: empatados dividem a posição e a seguinte é pulada
       */
      ranking: number;
      /** Participacao Percentual */
      participacao_percentual: string | null;
    };
    /**
     * TipoPessoa
     * @enum {string}
     */
    TipoPessoa: "PJ" | "PF" | "PE";
    /** ValorMensalResponse */
    ValorMensalResponse: {
      /**
       * Mes
       * Format: date
       * @description Primeiro dia do mês
       */
      mes: string;
      /** Contratacoes */
      contratacoes: number;
      /** Itens */
      itens: number;
      /** Valor Total Estimado */
      valor_total_estimado: string;
      /** Media Movel 3M */
      media_movel_3m: string;
      /**
       * Meses Na Media
       * @description Menor que 3 nos primeiros meses da série
       */
      meses_na_media: number;
    };
    /** ErroCampo */
    ErroCampo: {
      /** Campo */
      campo: string;
      /** Mensagem */
      mensagem: string;
    };
    /** ProblemDetail */
    ProblemDetail: {
      /**
       * Type
       * @default about:blank
       */
      type?: string;
      /** Title */
      title: string;
      /** Status */
      status: number;
      /**
       * Detail
       * @default null
       */
      detail?: string | null;
      /**
       * Instance
       * @default null
       */
      instance?: string | null;
      /**
       * Erros
       * @default null
       */
      erros?: components["schemas"]["ErroCampo"][] | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  listar_contratacoes_contratacoes_get: {
    parameters: {
      query?: {
        /** @description Página desejada (1 = primeira) */
        pagina?: number;
        /** @description Itens por página */
        tamanho_pagina?: number;
        uf?: string | null;
        orgao?: string | null;
        categoria?: string | null;
        /** @description Publicadas a partir deste dia */
        data_inicio?: string | null;
        /** @description Publicadas até este dia (inclusive) */
        data_fim?: string | null;
        /** @description Valor total estimado mínimo */
        valor_min?: number | string | null;
        /** @description Valor total estimado máximo */
        valor_max?: number | string | null;
        /** @description `-` na frente = decrescente */
        ordenar?: components["schemas"]["Ordenacao"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginaResponse_ContratacaoResponse_"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  detalhar_contratacao_contratacoes__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Número de controle PNCP com '-' no lugar de '/' */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContratacaoDetalheResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  listar_orgaos_orgaos_get: {
    parameters: {
      query?: {
        /** @description Página desejada (1 = primeira) */
        pagina?: number;
        /** @description Itens por página */
        tamanho_pagina?: number;
        uf?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginaResponse_OrgaoResponse_"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  listar_categorias_categorias_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoriaResponse"][];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  valor_mensal_metricas_valor_mensal_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValorMensalResponse"][];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  preco_categoria_metricas_preco_categoria_get: {
    parameters: {
      query?: {
        categoria?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrecoCategoriaResponse"][];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  ranking_fornecedores_metricas_ranking_fornecedores_get: {
    parameters: {
      query?: {
        orgao?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RankingFornecedorResponse"][];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  precos_acima_p90_metricas_precos_acima_p90_get: {
    parameters: {
      query?: {
        /** @description Página desejada (1 = primeira) */
        pagina?: number;
        /** @description Itens por página */
        tamanho_pagina?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginaResponse_PrecoAcimaP90Response_"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
}
